import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Header from "../component/header";
import Checkbox from "@mui/material/Checkbox";
import FormGroup from "@mui/material/FormGroup";
import FormControlLabel from "@mui/material/FormControlLabel";

export default function Home() {
    return (
        <div>
            <Head>
                <title>DHU portal to Google Cal.</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            <Header isLogin={true}></Header>
            <main className={styles.main}>
                <h1 className={styles.title}>DHU portal to Google Calendar</h1>
                <p>デジキャンから時間割を読み取り、googleカレンダーにイベントを追加します。</p>
                <p>機能を利用するにはgoogleでログインする必要があります。</p>
                <FormGroup>
                    <FormControlLabel control={<Checkbox />} label="1Q" />
                    <FormControlLabel control={<Checkbox />} label="2Q" />
                    <FormControlLabel control={<Checkbox />} label="3Q" />
                    <FormControlLabel control={<Checkbox />} label="4Q" />
                </FormGroup>
            </main>

            <footer className={styles.footer}></footer>
        </div>
    );
}
